services:
  magiclists:
    build:
      context: .
      dockerfile: Dockerfile
    image: magiclists-custom:local
    container_name: magiclists
    ports:
      - "4534:8000"
    env_file:
      - ../.env
    environment:
      - DATABASE_PATH=/app/data/magiclists.db
    volumes:
      - ../state:/app/data
    restart: unless-stopped
